### ISSUE TITLE
List<StudentForm>

### ISSUE THREAD

**Issue by arya009** [dotnet-labs/HerokuContainer#1]
I am trying to have multiple forms submitted in the example given. 

`public async Task<ActionResult<FormSubmissionResult>> SubmitMultipleForm([FromForm] List<StudentForm> form)`

But when I am running it shows big textbox to add items. It doesnt show the File Upload to select the controls. Do I have to give anything else to enable multiple file upload like this?

**Comment by changhuixu** [comment]
Form submission is for a single form. You can put multiple files in your form (singular).
